export const enum Units {
    Woodcutter                  = 'hF00',
    Militia                     = 'hF01',
    Enforcer                    = 'hF02',
    Footman                     = 'hF03',
    Swordsman                   = 'hF04',
    Captain                     = 'hF05',
    HorsemanKnight              = 'hF06',
    Guardian                    = 'hF07',
    Templar                     = 'hF08',
    HolyKnight                  = 'hF09',

    Peasant                     = 'hR00',
    Rogue                       = 'hR01',
    SpearThrower                = 'hR02',
    Archer                      = 'hR03',
    Ranger                      = 'hR04',
    Rifleman                    = 'hR05',
    Sharpshooter                = 'hR06',
    MortarTeam                  = 'hR07',
    FlyingMachine               = 'hR08',
    GryphonRider                = 'hR09',

    CacoDemon                   = 'nD0J',
    EvilEye                     = 'nD0K',
    Gargoyle                    = 'nD0L',
    VileTemptress               = 'nD0M',
    Hydralisk                   = 'nD0N',
    Destroyer                   = 'nD0O',
    Ocula                       = 'nD0P',
    DemonLord                   = 'nD0Q',
    EredarSorcerer              = 'nD0R',
    Overfiend                   = 'nD0S',

    Wig                         = 'nD00',
    FelHound                    = 'nD01',
    ClawDevil                   = 'nD02',
    FelGuard                    = 'nD03',
    FacelessOne                 = 'nD04',
    Oni                         = 'nD05',
    DemonSlasher                = 'nD06',
    DemonBlademaster            = 'nD07',
    DoomGuard                   = 'nD08',
    PitLord                     = 'nD09',
}